### ISSUE TITLE
panic on obfuscation

### ISSUE THREAD

**Issue by hazcod** [unixpickle/gobfuscate#41]
```
% ~/Source/go/bin/gobfuscate -verbose -winhide foo fooobfuscated     
2021/01/07 12:34:08 Copying GOPATH...
2021/01/07 12:34:11 Obfuscating package names...
2021/01/07 12:34:14 Obfuscating strings...
2021/01/07 12:34:14 Obfuscating symbols...
Renamed 2 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 1 occurrence in 1 file in 1 package.
Renamed 3 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 4 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 1 occurrence in 1 file in 1 package.
Renamed 1 occurrence in 1 file in 1 package.
Renamed 3 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 13 occurrences in 1 file in 1 package.
Renamed 1 occurrence in 1 file in 1 package.
Renamed 15 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 7 occurrences in 1 file in 1 package.
Renamed 1 occurrence in 1 file in 1 package.
Renamed 5 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.
Renamed 2 occurrences in 1 file in 1 package.

[Verbose] Temporary path: /var/folders/vg/39v449yj7rq8t72dl5gh20r00000gn/T/886489203
[Verbose] Go build command: go build -ldflags -s -w -H=windowsgui -extldflags '-static' -tags  -o fooobfuscated lfdhelhkhpoolioahefm

# lfdhelhkhpoolioahefm
adddynlib: unsupported binary format
adddynlib: unsupported binary format
adddynlib: unsupported binary format
runtime.firstmoduledata: unreachable sym in relocation: .rel
panic: should never happen

goroutine 1 [running]:
cmd/link/internal/ld.addToTextp(0xc00006f880)
	/usr/local/Cellar/go/1.15.6/libexec/src/cmd/link/internal/ld/lib.go:2823 +0x225
cmd/link/internal/ld.(*Link).loadlibfull(0xc00006f880, 0xc000ea2000, 0x101df, 0x101df, 0x200001)
	/usr/local/Cellar/go/1.15.6/libexec/src/cmd/link/internal/ld/lib.go:2853 +0x17d
cmd/link/internal/ld.Main(0x14729e0, 0x20, 0x20, 0x1, 0x7, 0x10, 0x0, 0x0, 0x12d8822, 0x1b, ...)
	/usr/local/Cellar/go/1.15.6/libexec/src/cmd/link/internal/ld/main.go:341 +0x18cc
main.main()
	/usr/local/Cellar/go/1.15.6/libexec/src/cmd/link/main.go:68 +0x1dc
Failed to compile: exit status 2
```

**Comment by hazcod** [comment]
Related to my build, apologies.
